### ISSUE TITLE
Logo in Dark Mode

### ISSUE THREAD

**Issue by sadrasabouri** [oxydev/SubsCrypt-npm-library#14]
Hi folks. Hope you do well.
I think your `README.md`'s logo is not that much clear and representative in Github dark mode.
Maybe you should transform it into a white-back-grounded one instead of transform-backgrounded.
Also it'll be nice if you move it to the center of page in terms of symmetric aspects.

By the way nice job :+1:.

**Comment by SaberDoTcodeR** [comment]
Thanks for pointing it out.
